site_dir: "site"
site_url: https://docs.zhoujie218.top
site_name: 周杰个人博客 - 记录生活点滴
site_description: 'zhoujie,zhoujie218,zhoujie218.top,周杰,个人博客,记录生活,点滴'

# Docs 
docs_dir: "docs"

# Repository
repo_name: Knowledge-Garden
repo_url: https://github.com/vbskycn/zhoujie_docs
edit_uri: edit/main/docs/
site_author: Steven Shum

# Copyright
copyright: 版权所有
