site_dir: "site"
site_url: https://docs.zhoujie218.top
site_name: 周杰个人博客 - 记录生活点滴
site_description: 'zhoujie,zhoujie218,zhoujie218.top,周杰,个人博客,记录生活,点滴'

# Docs 
docs_dir: "docs"

# Repository
repo_name: Knowledge-Garden
repo_url: https://github.com/vbskycn/zhoujie_docs
edit_uri: edit/main/docs/
site_author: Steven Shum

# Copyright
copyright: 版权所有

theme:
  name: material
  language: zh
  custom_dir: overrides
  favicon: assets/logo.ico
  logo: assets/octocat.png
  font:
    text: "Microsoft Yahei"
    code: "Consolas,Courier,courier new,stkaiti,kaiti,simkai,monospace"
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.sections
    - navigation.path         
    - content.action.edit
    - content.action.view
    - content.code.copy
    - navigation.footer
  palette:
    - scheme: default
      primary: grey
      accent: indigo
      toggle:
        icon: material/theme-light-dark
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      accent: indigo
      toggle:
        icon: material/theme-light-dark
        name: Switch to light mode
    
markdown_extensions:
    - admonition
    - pymdownx.details
    - md_in_html
    - pymdownx.superfences
    - smarty
    - toc:
        permalink: True
        separator: "-"
        toc_depth: 5
        slugify: !!python/object/apply:pymdownx.slugs.slugify
            kwds:
                case: lower
    - pymdownx.highlight
    - pymdownx.arithmatex:
        generic: true


hooks:
  - hooks.py
  - meta_slugs.py
      
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vbskycn
      name: GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/vbskycn
      name: Twitter      
    - icon: fontawesome/brands/mastodon
      link: https://genomic.social/@vbskycn
      name: Mastodon
  analytics:
    provider: custom
    property: foobar

extra_css:
  - css/extra.css

extra_javascript:
    - js/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.bootcss.com/mathjax/3.0.5/es5/tex-mml-chtml.js      
